@startuml bai6
class Student {
    - std::string name
    - int age
    - std::string hometown
    - std::string className
    --
    + Student(const std::string& name, int age, const std::string& hometown, const std::string& className)
    + std::string getName() const
    + int getAge() const
    + std::string getHometown() const
    + std::string getClassName() const
}

class ManagerStudent {
    - std::vector<std::shared_ptr<Student>> students
    --
    + void addStudent(const std::shared_ptr<Student>& student)
    + void displayStudentsByAge(int age) const
    + int countStudentsByAgeAndHometown(int age, const std::string& hometown) const
}

ManagerStudent o--> Student  


@enduml
